name: CI Checks

on:
  pull_request:
    branches:
      - main

concurrency: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code 🗄
        uses: actions/checkout@v3

      - name: Setup NodeJS 16 💿
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Setup Cache 🗂
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Install packages 🏭
        run: npm ci

      - name: Lint the code 🕵
        run: npm run lint

      - name: Run Prettier 💅
        run: npm run prettier

      - name: Run unit tests 🔬
        run: npm run test

      - name: Build code 🛠
        run: npm run build
